services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  web:
    build:
      args:
        user: zstrikke
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
      target: web
    command: sh -c "./wait-for-it.sh mysql:3306 -t 30 && ./wait-for-it.sh redis:6379 -t 30 && php-fpm"
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app
      - ./config:/usr/src/config
      - ./database:/usr/src/database
      - ./routes:/usr/src/routes
      - ./storage:/usr/src/storage
      - ./tests:/usr/src/tests
      - ./composer.json:/usr/src/composer.json
      - ./composer.lock:/usr/src/composer.lock
      - ./.env:/usr/src/.env
      - ./deployment/config/php-fpm/php-dev.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - update
      - mysql
      - redis

  scheduler:
    build:
      args:
          user: zstrikke
          uid: 1000
      context: .
      dockerfile: ./Dockerfile
      target: scheduler
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app
      - ./config:/usr/src/config
      - ./database:/usr/src/database
      - ./routes:/usr/src/routes
      - ./storage:/usr/src/storage
      - ./tests:/usr/src/tests
      - ./composer.json:/usr/src/composer.json
      - ./composer.lock:/usr/src/composer.lock
      - ./.env:/usr/src/.env
    depends_on:
      - update
      - mysql
      - redis

  worker:
    build:
      args:
        user: zstrikke
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
      target: worker
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app
      - ./config:/usr/src/config
      - ./database:/usr/src/database
      - ./routes:/usr/src/routes
      - ./storage:/usr/src/storage
      - ./tests:/usr/src/tests
      - ./composer.json:/usr/src/composer.json
      - ./composer.lock:/usr/src/composer.lock
      - ./.env:/usr/src/.env
    depends_on:
      - update
      - mysql
      - redis

  mysql:
    build:
      args:
        password: ${DB_PASSWORD}
      context: .
      dockerfile: ./Dockerfile.mysql
    restart: unless-stopped
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    volumes:
      - ./redisdata:/data
    ports:
      - "63790:6379"

  update:
    build:
      args:
        user: zstrikke
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "./wait-for-it.sh mysql:3306 -t 30 && ./update.sh"
    restart: no
    volumes:
      - ./composer.json:/usr/src/composer.json
      - ./composer.lock:/usr/src/composer.lock
      - ./.env:/usr/src/.env
      - ./deployment/bin/update.sh:/usr/src/update.sh
    depends_on:
      - mysql
